### ISSUE TITLE
replication - metrics pod is pending

### ISSUE THREAD

**Issue by n7qnm** [mariadb-operator/mariadb-operator#464] opened 2024-03-16 04:35 UTC
Ran the mariadb_replication_full.yaml - all the pods come up EXCEPT - repl-metrics, which stays in a pending state.    

Am I missing something?

**Comment by mmontes11** [comment] 2024-03-18 09:22
Hey @n7qnm ! This is a duplicate of:
- https://github.com/mariadb-operator/mariadb-operator/issues/442

A fix has been merged already and will be released in `v0.0.28`, stay tuned!

**Closed** 2024-03-23 18:01 UTC
Labels: duplicate
