### ISSUE TITLE
[Bug] Cannot delete `Grant` CRD

### ISSUE THREAD

**Issue by matthieugusmini** [mariadb-operator/mariadb-operator#172] opened 2023-07-28 06:02 UTC
**Describe the bug**
When I'm trying to delete the CRD with the following command it does't get deleted:
```shell
kubectl delete --force grants.mariadb.mmontes.io foo
```

**Expected behaviour**
The deployed `Grant` should be deleted.

**Steps to reproduce the bug**
Deploy a `Grant` with a non existent database table. Here's the YAML file I used to deploy the CRD:
```yaml
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: foo
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
  database: "mysql"
  table: "proxies-priv"
  username: maxscale
  grantOption: false
```
(It should be `mysql.proxies_priv`)

**Additional context**
Not an expert but I suspect a deadlock in the finalizer 🤔 Don't really have the time to inspect further right now but might give it a look later.
Following the instructions from [this answer](https://github.com/kubernetes/kubernetes/issues/60538#issuecomment-1039128094) I eventually deleted the CRD.

**Environment details**:
- Kubernetes version: 
```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.14-gke.1200
```
- mariadb-operator version: v0.0.18
- Install method: helm
- Install flavour: custom

**Comment by mmontes11** [comment] 2023-07-28 07:19
Hey there @matthieugusmini ! Thanks again for reporting this.

> Not an expert but I suspect a deadlock in the finalizer thinking Don't really have the time to inspect further right now but might give it a look later.

Good catch, the problem is that we are setting the finalizer in the first place, even if the SQL resource hasn't been reconciled:
https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/sql/controller.go#L45..L47

The SQL resource is invalid and therefore is not created in the database at any point, the controller will be erroring trying to reconcile. At this point, if we delete the resource as you did, finalizing the resource will fail because the controller will be trying to delete a non existing resource:
https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/sql/finalizer.go#L65..L67

The solution for this may be moving [this block](https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/sql/controller.go#L45..L47) to the end of the reconciliation logic [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/pkg/controller/sql/controller.go#L96), after the resource has successfully been reconciled. Feel free to give it a try and raise a PR. I will try to have a look as well when I find some time 😃 

Thanks!

**Comment by mmontes11** [comment] 2023-07-28 15:15
After merging your [PR](https://github.com/mariadb-operator/mariadb-operator/pull/174), the finalizers are correctly set only after the resource is reconciled in the database. I've managed to delete a `Grant` pointing to a non existing user without hassle. Closing!

**Closed by mmontes11** 2023-07-28 15:15 UTC
Labels: bug

**Comment by plsnotracking** [comment] 2024-04-18 05:31
Is there a way to delete this correctly? I have it deployed and am having a hard time removing.
```bash
❯ for crd in `kubectl get crds -oname | grep mariadb.com | awk -F / '{ print $2 }'`; do kubectl delete crd $crd; done
customresourcedefinition.apiextensions.k8s.io "grants.k8s.mariadb.com" deleted
customresourcedefinition.apiextensions.k8s.io "users.k8s.mariadb.com" deleted
```
The programme is stuck at this point and wouldn't move forward.

Thanks.
