### ISSUE TITLE
[Bug] mariadb-operator panics due to null pointer

### ISSUE THREAD

**Issue by luohaha3123** [mariadb-operator/mariadb-operator#582] opened 2024-04-24 11:31 UTC
**Documentation**
- [ ] I acknowledge that I have read the relevant [documentation](https://github.com/mariadb-operator/mariadb-operator/tree/main/docs).

**Describe the bug**
The mariadb-operator is experiencing a panic due to the absence of null pointer checks for certain variables. As a result, the operator is unable to function properly.

![20240424192844259](https://github.com/mariadb-operator/mariadb-operator/assets/70438293/85ae4794-4cfe-407d-8462-edd02e0b3fc4)

**Environment details**:
- Kubernetes version: [v1.18.3]
- mariadb-operator version: [0.0.27]
- Install method: [helm]
- Install flavor: [ custom]

**Additional context**

**Comment by mmontes11** [comment] 2024-04-24 11:34
Duplicate of https://github.com/mariadb-operator/mariadb-operator/issues/491. Fixed by https://github.com/mariadb-operator/mariadb-operator/pull/492

To be released in `v0.0.28`

**Closed by mmontes11** 2024-04-24 11:34 UTC
Labels: bug

**Comment by luohaha3123** [comment] 2024-04-25 01:06
@mmontes11 Thanks
